modLoader="javafml"
loaderVersion="[31,)" 

[[mods]]
    modId="huntermod"
    version="1.0.5"
    displayName="Hunter Mod"
	authors="Xrated_junior"
    description='''
    This mod adds a Hunter mob.
    '''
    
[[dependencies.huntermod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"